format="$all$directory$character"

# Inserts a blank line between shell prompts
add_newline = true

[character] 
error_symbol = "[x](red)"
success_symbol = "[](green)"
vimcmd_replace_symbol = "[](green)"
vimcmd_symbol = "[](green)"
vimcmd_visual_symbol = "[](yellow)"

# Disable the package module, hiding it from the prompt completely
# [package]
#disabled = false

[python]
disabled = true

[aws]
format = '[$symbol($profile ) (\[$duration\])]($style) '
symbol = ' '
disabled = true

[conda]
format = "[$symbol$environment]($style) "

[git_branch]
symbol = ' '

[vcsh]
format = '[$repo  ]($style)'

[shell]
xonsh_indicator=":shell:"